{% set name = "skill-unit-test" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - path: ../src
    folder: src
  - path: ../skill-unit-test.init.ils

build:
  number: 1

requirements:
  run:
    - ids-skill

about:
  home: https://github.com/skyworksinc/skill-unit-test
  license: proprietary
  summary: SKILL unit test framework
  description: |
    A unit testing framework for the Cadence SKILL language.
  dev_url: https://github.com/skyworksinc/skill-unit-test
